Readd keyboard sample (fixed a typo)
OpenOrbis/OpenOrbis-PS4-Toolchain pull request #183
Opened 2022-01-02 12:46 UTC by Klairm

So I've testing the old keyboard sample so many times and couldn't figure what was the problem, until I noticed that the font path in the InitFont func was wrong, fixing that typo makes it works again!

2022-01-05 15:41 UTC, darkxex commented
Nice work man

2022-01-06 15:23 UTC, kiwidoggie requested changes
Can you remove the binaries (*.prx/*.sprx) and verify that this still works under 0.5.2?

2022-01-07 15:22 UTC, Klairm commented
> Can you remove the binaries (_.prx/_.sprx) and verify that this still works under 0.5.2?

Done, for me it works correctly using the 0.5.2 release

2022-01-09 21:12 UTC, kiwidoggie approved these changes

2022-01-09 21:12 UTC, merged