Add Trophy Support and add a sample for the trophy system
OpenOrbis/OpenOrbis-PS4-Toolchain pull request #188
Opened 2022-01-07 07:26 UTC by Backporter

2022-01-09 21:14 UTC, kiwidoggie requested changes
Can you remove all of the extra sprx/prx binaries, they need to be compiled from source and copied in. Will review other changes later.

2022-01-09 21:17 UTC, Backporter commented
totally forgot to remove them, doing that now.

2022-01-12 22:27 UTC, Cryptogenic requested changes
Overall, need title ID/content ID updated to BREW00094, Makefile needs to be added, and icon0 should be updated (it's currently identical to audio wav sample).

2022-01-12 22:27 UTC, Cryptogenic commented on samples/trophies/trophies/build.bat
> +set PKG_TITLE_ID="BREW00080"
Title ID and content ID need updating, BREW00080 conflicts with audio wav sample. Recommend BREW00094. Makefile also needs to be written for samples for linux compatibility.

2022-01-14 02:33 UTC, Backporter commented
should be good now?

2022-01-15 17:39 UTC, bucanero commented on include/orbis/_types/rtc.h
> +} SceRtcTick;
I think this should be:

```suggestion
}OrbisRtcTick;
```

2022-01-15 17:40 UTC, Backporter commented on include/orbis/_types/rtc.h
> +} SceRtcTick;
Right, missed that, fixing now.

2022-01-19 23:57 UTC, merged